name: Build & Nightly Release

on:
  push:
    branches: [ "main", "dev", "*" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repo klonlanıyor
        uses: actions/checkout@v3

      - name: Java 21 kuruluyor
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Gradle önbellekleme
        uses: gradle/gradle-build-action@v2

      - name: Derleme başlatılıyor
        run: ./gradlew build

      - name: Benzersiz JAR dosyalarını ayıkla
        id: find_jars
        run: |
          mkdir filtered-jars
          for file in $(find . -type f -name '*.jar' -path '*/build/libs/*'); do
            base=$(basename "$file")
            dest="filtered-jars/$base"
            if [ ! -e "$dest" ]; then
              cp "$file" "$dest"
            fi
          done
          echo "all_jars=$(find filtered-jars -type f -name '*.jar' | paste -sd ',' -)" >> $GITHUB_OUTPUT

      - name: GitHub Releases’a yükle
        uses: softprops/action-gh-release@v1
        with:
          tag_name: nightly-${{ github.run_number }}
          name: "Gece Sürümü #${{ github.run_number }}"
          body: "Bu otomatik olarak oluşturulmuş bir gece sürümüdür (nightly build)."
          prerelease: true
          files: ${{ steps.find_jars.outputs.all_jars }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
